export const LOAD_POSTS = 'LOAD_POSTS'
export const ADD_POST = 'ADD_POST'
export const TOGGLE_BOOKMARK = 'TOGGLE_BOOKMARK'
export const SET_ACTIVE_POST = 'SET_ACTIVE_POST'
export const DETELE_POST = 'DETELE_POST'
